# Generated by Django 5.0.7 on 2024-09-26 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kbhs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('is_boarder', models.BooleanField(default=False)),
                ('dormitory', models.CharField(max_length=100)),
            ],
        ),
    ]
